# Setup
title:               Yogesh Dhimate
tagline:             'Notes to Myself'
description:         ''
url:                 https://dhimate.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Yogesh Dhimate
  url:               https://www.linkedin.com/in/dhimate/
  email:             dhimate@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
